kopia_client__op_vault: "Applications"
kopia_client__op_key: "{{ 'KOPIA_' + inventory_hostname }}"
kopia_client__hostname: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        field='hostname'
      )
  }}
kopia_client__backup_schedule: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        field='OnCalendar'
      )
  }}
kopia_client__backup_destination: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        field='destination'
      )
  }}
kopia_client__username: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        field='username'
      )
  }}
kopia_client__password: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        field='password'
      )
  }}
kopia_client__snapshot_command: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        field='snapshot-command'
      )
  }}
