apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/ansible_collection
    contents:
      - path: community.general
        git:
          url: https://github.com/ansible-collections/community.general
          ref: 9.5.1
          depth: 1
      - path: hetzner.cloud
        git:
          url: https://github.com/ansible-collections/hetzner.hcloud
          ref: origin/tags/4.2.1
          depth: 1
  - path: vendor/ansible_roles
    contents:
      - path: unattended_upgrades
        git:
          url: https://github.com/hifis-net/ansible-collection-toolkit
          ref: v5.1.0
          depth: 1
        includePaths:
          - roles/unattended_upgrades/**/*
        newRootPath: roles/unattended_upgrades
