apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/ansible_collection
    contents:
      - path: community.general
        git:
          url: https://github.com/ansible-collections/community.general
          ref: 10.2.0
          depth: 1
      - path: hetzner.cloud
        git:
          url: https://github.com/ansible-collections/hetzner.hcloud
          ref: 4.2.2
          depth: 1
  - path: vendor/ansible_roles
    contents:
      - path: unattended_upgrades
        git:
          url: https://github.com/hifis-net/ansible-collection-toolkit
          ref: v5.2.1
          depth: 1
        includePaths:
          - roles/unattended_upgrades/**/*
        newRootPath: roles/unattended_upgrades
  - path: vendor/pve-nag-buster
    contents:
      - path: .
        git:
          url: https://github.com/foundObjects/pve-nag-buster
          ref: origin/master
          depth: 1
  - path: vendor/exporters
    contents:
      - path: pve_exporter
        git:
          url: https://github.com/prometheus-pve/prometheus-pve-exporter
          ref: v3.5.1
          depth: 1
        includePaths:
          - src/pve_exporter/**/*
        newRootPath: src/pve_exporter
      - path: textfile-collector-scripts
        git:
          url: https://github.com/prometheus-community/node-exporter-textfile-collector-scripts
          ref: origin/master
          depth: 1
        includePaths:
          - zfs*
      - path: pbs-exporter
        # https://github.com/natrontech/pbs-exporter
        githubRelease:
          slug: natrontech/pbs-exporter
          tag: v0.6.4
          # Can't sync checksums with variable release tags...
          disableAutoChecksumValidation: true
          assetNames:
            - "pbs-exporter_v*_linux_amd64.tar.gz"
          unpackArchive:
            path: "pbs-exporter_v0.6.4_linux_amd64.tar.gz"
