- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Restart networking
  ansible.builtin.systemd_service:
    name: networking
    state: restarted
- name: Update Grub
  ansible.builtin.command: update-grub
  register: _pve_grub_update
  failed_when: ('error' in _pve_grub_update.stderr)
  tags: skiponlxc
- name: Update Initramfs
  ansible.builtin.command: update-initramfs -u -k all
