---
- name: Modify vfio IOMMU references and configuration in default grub
  ansible.builtin.blockinfile:
    dest: /etc/default/grub
    marker: "# {mark}: IOMMU default grub configuration (managed by ansible)."
    content: "\
      GRUB_CMDLINE_LINUX=\"$GRUB_CMDLINE_LINUX intel_iommu=on\"\n\
      {% if (pve_iommu_passthrough_mode | default(true) | bool) %}GRUB_CMDLINE_LINUX=\"$GRUB_CMDLINE_LINUX iommu=pt\"\n{% endif %}\
      {% if (pve_mediated_devices_enabled | default(false) | bool) %}GRUB_CMDLINE_LINUX=\"$GRUB_CMDLINE_LINUX i915.enable_gvt=1 i915.enable_guc=0\"\n{% endif %}\
      {% if (pve_pci_device_ids | default([]) | length > 0) %}GRUB_CMDLINE_LINUX=\"$GRUB_CMDLINE_LINUX vfio-pci.ids={% for k in pve_pci_device_ids %}{{ k.id }}{% if k != (pve_pci_device_ids | last) %},{% endif %}{% endfor %}\"{% endif %}"
    insertafter: '^GRUB_CMDLINE_LINUX=""'
    mode: "0640"
  notify: Update Grub

- name: Create/Modify modprobe.d configuration files
  block:
    - name: Specify vfio configuration options
      notify: Update Initramfs
      ansible.builtin.blockinfile:
        dest: /etc/modprobe.d/vfio.conf
        marker: "# {mark}: VFIO driver configuration options (managed by ansible)."
        content: "\
          {% if (pve_vfio_blacklist_drivers | default([]) | length > 0) %}{% for k in pve_vfio_blacklist_drivers %}softdep {{ k.name }} pre: vfio-pci\n{% endfor %}{% endif %}\
          {% if (pve_pcie_ovmf_enabled | default(false) | bool) %}options vfio-pci disable_vga=1\n{% endif %}\
          {% if (pve_pci_device_ids | default([]) | length > 0) %}options vfio-pci
          ids={% for k in pve_pci_device_ids %}{{ k.id }}{% if k != (pve_pci_device_ids | last) %},{% endif %}{% endfor %}{% endif %}"
        mode: "0640"
        create: true
      when: >
        (pve_vfio_blacklist_drivers | default([]) | length > 0) or
        (pve_pci_device_ids | default([]) | length > 0) or
        (pve_pcie_ovmf_enabled | default(false) | bool)

    - name: Blacklist drivers from host
      notify: Update Initramfs
      ansible.builtin.blockinfile:
        dest: /etc/modprobe.d/blacklist.conf
        marker: "# {mark}: Blacklist drivers from host (managed by ansible)."
        content: "{% for k in pve_vfio_blacklist_drivers %}blacklist {{ k.name }}\n{% endfor %}"
        mode: "0640"
        create: true
      when: >
        (pve_vfio_blacklist_drivers | default([]) | length > 0)

    - name: Specify kvm configuration options
      notify: Update Initramfs
      ansible.builtin.blockinfile:
        dest: /etc/modprobe.d/kvm.conf
        marker: "# {mark}: VFIO driver configuration options (managed by ansible)."
        content: "\
          {% if (pve_pcie_ignore_msrs | bool) %}options kvm ignore_msrs=1\n{% endif %}\
          {% if (not pve_pcie_report_msrs | bool) %}options kvm report_ignored_msrs=0{% endif %}"
        mode: "0640"
        create: true
      when: >
        (pve_pcie_ignore_msrs | default(false) | bool) or
        (not pve_pcie_report_msrs | default(true) | bool)

- name: Modify required modules list
  block:
    - name: Modify modules list for PCIe Passthrough
      notify: Update Initramfs
      ansible.builtin.blockinfile:
        dest: /etc/modules
        marker: "# {mark}: Modules required for PCI passthrough (managed by ansible)."
        content: |
          vfio
          vfio_iommu_type1
          vfio_pci
          vfio_virqfd

    - name: Modify modules list for GVT-g
      notify: Update Initramfs
      ansible.builtin.blockinfile:
        dest: /etc/modules
        marker: "# {mark}: Modules required for GVT-g (managed by ansible)."
        content: |
          kvmgt
          mdev
      when: >
        (pve_mediated_devices_enabled | default(false) | bool)
