zfs__op_vault: "Applications"
zfs__op_key: "{{ 'ZFS_' + inventory_hostname }}"
zfs__encryption_key: |-
  {{
      lookup(
        'community.general.onepassword',
        zfs__op_key,
        vault=zfs__op_vault,
        field='password'
      )
  }}
