- name: Config tool
  ansible.builtin.template:
    src: data/wireguard/configure.j2
    dest: /data/wireguard/configure
    mode: "0755"

- name: Config
  ansible.builtin.copy:
    content: "{{ wireguard__config_wgsrv1 }}"
    dest: /data/wireguard/wgsrv1.conf
    mode: "0600"
  notify:
    - Configure Wireguard

- name: Install service
  ansible.builtin.copy:
    src: etc/systemd/system/wireguard-config.service
    dest: /etc/systemd/system/wireguard-config.service
    mode: "0644"
  notify:
    - Reload systemd

- name: Install timer
  ansible.builtin.copy:
    src: etc/systemd/system/wireguard-config.timer
    dest: /etc/systemd/system/wireguard-config.timer
    mode: "0644"
  notify:
    - Reload systemd

- name: Enable timer
  ansible.builtin.systemd:
    name: wireguard-config.timer
    state: started
    enabled: true
