wireguard__op_vault: "Applications"
wireguard__op_key: "{{ 'WIREGUARD_' + inventory_hostname }}"
wireguard__port: 51820
wireguard__address: |-
  {{
      lookup(
        'community.general.onepassword',
        wireguard__op_key,
        vault=wireguard__op_vault,
        field='Address'
      )
  }}
wireguard__private_key: |-
  {{
      lookup(
        'community.general.onepassword',
        wireguard__op_key,
        vault=wireguard__op_vault,
        field='password'
      )
  }}
wireguard__peers: |-
  {{
      lookup(
        'community.general.onepassword',
        wireguard__op_key,
        vault=wireguard__op_vault,
        field='peers'
      )
  }}
# Special field for unifi
wireguard__ipv6: |-
  {{
      lookup(
        'community.general.onepassword',
        wireguard__op_key,
        vault=wireguard__op_vault,
        field='ipv6'
      )
  }}
