wireguard__op_vault: "Applications"
wireguard__op_key: "{{ 'WIREGUARD_' + inventory_hostname }}"
wireguard__port: 51820
wireguard__config_wg0: |
  {{
      lookup(
        'community.general.onepassword',
        'WIREGUARD_' + inventory_hostname + '_WG0',
        vault=wireguard__op_vault,
        field='notesPlain'
      )
  | from_markdown | very_mandatory
  }}
