mailx__op_vault: "Applications"
mailx__op_key: "MAILX"
mailx__mta: |-
  {{
      lookup(
        'community.general.onepassword',
        mailx__op_key,
        vault=mailx__op_vault,
        field='password'
      )
  }}
mailx__domain: |-
  {{
      lookup(
        'community.general.onepassword',
        mailx__op_key,
        vault=mailx__op_vault,
        field='domain'
      )
  }}
