- name: Install packages
  ansible.builtin.apt:
    pkg:
      - docker.io
      - docker-compose-v2
      - redir
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Copy redir services
  block:
    - name: Copy redir-80
      ansible.builtin.copy:
        src: etc/systemd/system/redir-80.service
        dest: /etc/systemd/system/
        mode: "0644"
      notify: Restart redir-80

    - name: Copy redir-443
      ansible.builtin.copy:
        src: etc/systemd/system/redir-443.service
        dest: /etc/systemd/system/
        mode: "0644"
      notify: Restart redir-443

- name: Enable and start redir services
  block:
    - name: Enable and start redir-80
      ansible.builtin.service:
        name: redir-80
        state: started
        enabled: true

    - name: Enable and start redir-443
      ansible.builtin.service:
        name: redir-443
        state: started
        enabled: true
