- name: Hetzner Servers
  hosts: hcloud
  roles:
    - role: wireguard
      tags: wireguard
  tasks:
    - name: Basic setup
      tags: basic
      block:
        - name: Use NextDNS
          ansible.builtin.blockinfile:
            path: /etc/systemd/resolved.conf
            backup: true
            block: |
              DNS=45.90.28.0#{{ inventory_hostname | lower }}-{{ nextdns_id }}.dns.nextdns.io
              DNS=2a07:a8c0::#{{ inventory_hostname | lower }}-{{ nextdns_id }}.dns.nextdns.io
              DNS=45.90.30.0#{{ inventory_hostname | lower }}-{{ nextdns_id }}.dns.nextdns.io
              DNS=2a07:a8c1::#{{ inventory_hostname | lower }}-{{ nextdns_id }}.dns.nextdns.io
              DNSOverTLS=yes
              DNSStubListenerExtra=0.0.0.0
          notify: Restart DNS Resolver
        - name: Hosts file
          ansible.builtin.blockinfile:
            path: /etc/hosts
            block: "{{ lookup('ansible.builtin.file', inventory_dir + '/../.secrets/hosts') }}"
            backup: true
    - name: Mounts
      tags: mount
      block:
        - name: Install packages
          ansible.builtin.apt:
            pkg:
              - sshfs
              - gocryptfs
            state: present
            update_cache: true
            cache_valid_time: 3600
        - name: Allow fuse drives to be shared with docker
          ansible.builtin.lineinfile:
            path: /etc/fuse.conf
            line: user_allow_other
            backup: true
        - name: Create mount path
          ansible.builtin.file:
            path: "{{ bulk_storage.local_path }}"
            state: directory
            mode: "0755"
        - name: Set up mount
          ansible.posix.mount:
            path: "{{ bulk_storage.local_path }}"
            src: "{{ bulk_storage.remote_path }}"
            fstype: "{{ bulk_storage.type }}"
            opts: "{{ bulk_storage.options }}"
            state: mounted
  handlers:
    - name: Restart DNS Resolver
      ansible.builtin.systemd_service:
        name: systemd-resolved.service
        state: restarted
