- name: Guest Agent
  hosts: proxmox_all_qemu
  tasks:
    - name: Install guest agent
      ansible.builtin.apt:
        pkg: qemu-guest-agent
        state: present
        update_cache: true
        cache_valid_time: 3600
