- name: Unattended Upgrades
  hosts: hcloud proxmox_all_qemu proxmox_nodes proxmox_all_lxc
  tags:
    - unattended-upgrades
  roles:
    - role: mailx
      tags:
        - mailx
    - role: unattended_upgrades
