- name: Install node collector packages
  ansible.builtin.apt:
    pkg:
      - prometheus-node-exporter
      - moreutils
    state: present

- name: Enable node collector service
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter
    enabled: true
    state: started
