- name: Kopia Server
  block:
    - name: Install node collector packages
      ansible.builtin.apt:
        pkg:
          - prometheus-node-exporter
          - moreutils
        state: present

    - name: Enable node collector service
      ansible.builtin.systemd_service:
        name: prometheus-node-exporter
        enabled: true
        state: started

    - name: Copy kopia services
      ansible.builtin.copy:
        src: systemd/system/
        dest: /etc/systemd/system/
        mode: "0644"
      notify: Reload systemd

    - name: Copy kopia service templates
      ansible.builtin.template:
        src: "systemd/system/{{ item }}.service.j2"
        dest: /etc/systemd/system/
        mode: "0644"
      loop:
        - kopia-server
        - kopia-sync
      notify: Reload systemd

    - name: Copy kopia executables
      ansible.builtin.copy:
        src: usr/local/bin/
        dest: /usr/local/bin/
        mode: "0755"

    - name: Enable kopia services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - kopia-maintenance.timer
        - kopia-exporter.timer
        - kopia-sync.timer
        - kopia-server.service
