- name: Sanoid
  block:
    - name: Install sanoid packages
      ansible.builtin.apt:
        pkg:
          - sanoid
        state: present

    - name: Ensure sanoid config directory exists
      ansible.builtin.file:
        path: /etc/sanoid
        state: "directory"
        mode: "0755"

    - name: Copy sanoid config
      ansible.builtin.template:
        src: etc/sanoid/sanoid.conf.j2
        dest: /etc/sanoid/sanoid.conf
        mode: "0644"

    - name: Enable sanoid timer
      ansible.builtin.systemd_service:
        name: sanoid.timer
        enabled: true
        state: started

- name: Syncoid
  block:
    - name: Copy syncoid script
      ansible.builtin.template:
        src: usr/local/bin/syncoid-snapshot.j2
        dest: /usr/local/bin/syncoid-snapshot
        mode: "0755"

    - name: Copy syncoid service
      ansible.builtin.copy:
        src: etc/systemd/system/syncoid.service
        dest: /etc/systemd/system/syncoid.service
        mode: "0644"

    - name: Copy syncoid timer
      ansible.builtin.copy:
        src: etc/systemd/system/syncoid.timer
        dest: /etc/systemd/system/syncoid.timer
        mode: "0644"

    - name: Enable syncoid timer
      ansible.builtin.systemd_service:
        name: syncoid.timer
        enabled: true
        state: started
