- name: Configure rclone
  ansible.builtin.include_tasks:
    file: rclone.yaml

- name: Install
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Exporter
  ansible.builtin.include_tasks:
    file: exporter.yaml
