proxmox_backup_server__op_vault: "Applications"
proxmox_backup_server__op_key: "ProxmoxBackupServer"

proxmox_backup_server__rclone_destination: |-
  {{
      lookup(
        'community.general.onepassword',
        proxmox_backup_server__op_key,
        vault=proxmox_backup_server__op_vault,
        field='rclone_destination'
      ) | very_mandatory
  }}

proxmox_backup_server__exporter_token: |-
  {{
      lookup(
        'community.general.onepassword',
        proxmox_backup_server__op_key,
        vault=proxmox_backup_server__op_vault,
        field='pbs_exporter_token'
      ) | very_mandatory
  }}

proxmox_backup_server__network_domain: |-
  {{
      lookup(
        'community.general.onepassword',
        'network',
        vault=proxmox_backup_server__op_vault,
        field='domain'
      ) | very_mandatory
  }}

proxmox_backup_server__sync_account: |-
  {{
      lookup(
        'community.general.onepassword',
        proxmox_backup_server__op_key,
        vault=proxmox_backup_server__op_vault,
        field='sync_account'
      ) | very_mandatory
  }}

proxmox_backup_server__sync_key: |-
  {{
      lookup(
        'community.general.onepassword',
        proxmox_backup_server__op_key,
        vault=proxmox_backup_server__op_vault,
        field='sync_key'
      ) | very_mandatory
  }}
