- name: Install packages
  ansible.builtin.apt:
    pkg:
      - ufw
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Allow SSH
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "22"
  when: wireguard__allow_ssh is not defined or wireguard__allow_ssh

- name: Allow Wireguard
  community.general.ufw:
    rule: allow
    proto: udp
    port: "{{ wireguard__port }}"

- name: Set ufw logging
  community.general.ufw:
    logging: "on"

- name: Allow Traffic on Wireguard
  community.general.ufw:
    rule: allow
    proto: any
    interface_in: "wg0"

- name: Reject everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: reject
    log: true
