- name: Install packages
  ansible.builtin.apt:
    pkg:
      - ufw
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Allow Wireguard
  community.general.ufw:
    rule: allow
    proto: udp
    port: "{{ wireguard__port }}"

- name: Set ufw logging
  community.general.ufw:
    logging: "on"

- name: Allow Traffic on Wireguard
  community.general.ufw:
    rule: allow
    proto: any
    interface_in: "wg0"

- name: Allow forwarding sysctl
  ansible.builtin.blockinfile:
    path: /etc/ufw/sysctl.conf
    append_newline: true
    prepend_newline: true
    block: |
      net/ipv4/ip_forward=1
      net/ipv6/conf/default/forwarding=1
      net/ipv6/conf/all/forwarding=1
    state: present

- name: Reject everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: reject
    log: true
