- name: Look up item info
  ansible.builtin.set_fact:
    peers: |-
      {{
        peers | default([]) + [
          {
            'name': item,
            'public_key': lookup('community.general.onepassword', 'WIREGUARD_' + item, vault=wireguard__op_vault, field='username'),
            'preshared_key': lookup(
              'community.general.onepassword',
              wireguard__op_key,
              vault=wireguard__op_vault,
              section='PRESHAREDKEY',
              field=item
            ),
            'allowed_ips': lookup('community.general.onepassword', 'WIREGUARD_' + item, vault=wireguard__op_vault, field='AllowedIPs'),
            'endpoint': lookup('community.general.onepassword', 'WIREGUARD_' + item, vault=wireguard__op_vault, field='Endpoint'),
          }
        ]
      }}
  loop: "{{ wireguard__peers | split(',') | map('trim') }}"

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - wireguard
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Firewall
  ansible.builtin.import_tasks:
    file: firewall.yaml

- name: Config
  ansible.builtin.template:
    src: etc/wireguard/wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: "0600"
  notify:
    - Restart Wireguard

- name: Enable and start Wireguard service
  ansible.builtin.service:
    name: wg-quick@wg0
    state: started
    enabled: true
